"""
SatQuery AI - shared Pydantic schemas.

These are the contracts every layer of the pipeline talks through:
ingestion -> router -> engine -> evidence engine -> LLM synthesis -> API response.
Keeping them in one file means the "locked evidence object" the PRD calls for
is enforced by the type system, not by convention.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Modality(str, Enum):
    OPTICAL = "optical"
    SAR = "sar"
    UNKNOWN = "unknown"


class TaskType(str, Enum):
    SINGLE_IMAGE = "single_image"       # VQA + caption/grounding
    BI_TEMPORAL_CHANGE = "bi_temporal_change"
    CROSS_MODAL_FUSION = "cross_modal_fusion"


class SubTask(str, Enum):
    VQA = "vqa"
    CAPTION = "caption"
    GROUNDING = "grounding"
    CHANGE_VQA = "change_vqa"
    CHANGE_DESCRIPTION = "change_description"
    FUSION_ANALYSIS = "fusion_analysis"


# ---------------------------------------------------------------------------
# Input side
# ---------------------------------------------------------------------------

class ImageMeta(BaseModel):
    """Metadata attached to every uploaded/ingested image."""
    file_id: str
    path: str
    modality: Modality
    crs: Optional[str] = None
    resolution_m: Optional[float] = None
    bbox_latlon: Optional[List[float]] = None  # [min_lon, min_lat, max_lon, max_lat]
    cloud_cover_fraction: Optional[float] = Field(
        default=None, description="0-1, only meaningful for optical imagery"
    )
    capture_date: Optional[str] = None


class QueryRequest(BaseModel):
    """What the API endpoint receives after images are saved to disk."""
    query_text: str
    images: List[ImageMeta]


# ---------------------------------------------------------------------------
# Router output
# ---------------------------------------------------------------------------

class RouteDecision(BaseModel):
    """
    The agentic router's decision. Deliberately rule-based and fully
    serializable -- this IS the first entry of the graded execution trace.
    """
    task_type: TaskType
    sub_tasks: List[SubTask]
    reason: str
    image_count: int
    modalities: List[Modality]


# ---------------------------------------------------------------------------
# Evidence object (locked, deterministic, non-LLM)
# ---------------------------------------------------------------------------

class BoundingBox(BaseModel):
    min_lon: float
    min_lat: float
    max_lon: float
    max_lat: float


class EvidenceObject(BaseModel):
    """
    The ONLY numbers the LLM synthesis layer is allowed to talk about.
    Produced entirely by deterministic CV/GIS code (core/evidence_engine.py).
    Never touched or generated by an LLM. This is the hallucination firewall
    described in PRD section 4.2.
    """
    task_type: TaskType
    area_ha: Optional[float] = None
    change_area_ha: Optional[float] = None
    bbox_latlon: Optional[BoundingBox] = None
    confidence: float = Field(ge=0.0, le=1.0)
    land_cover_classes: List[str] = Field(default_factory=list)
    change_classes: List[str] = Field(default_factory=list)
    object_count: Optional[int] = None
    raw_scores: Dict[str, float] = Field(default_factory=dict)
    change_polygons_geojson: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="GeoJSON Feature list of vectorised change/detection polygons "
        "for map overlay. Each feature has geometry (Polygon) and properties "
        "(class, confidence, area_ha).",
    )
    notes: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Execution trace (this is what SIH26167 actually grades)
# ---------------------------------------------------------------------------

class TraceStep(BaseModel):
    step: str
    component: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    output_summary: str


class ExecutionTrace(BaseModel):
    steps: List[TraceStep] = Field(default_factory=list)

    def add(self, step: str, component: str, parameters: Dict[str, Any], output_summary: str) -> None:
        self.steps.append(
            TraceStep(step=step, component=component, parameters=parameters, output_summary=output_summary)
        )


# ---------------------------------------------------------------------------
# Final API response
# ---------------------------------------------------------------------------

class QueryResponse(BaseModel):
    answer: str
    evidence: EvidenceObject
    trace: ExecutionTrace
    route: RouteDecision
    input_image_urls: List[str] = Field(default_factory=list)
    result_image_url: Optional[str] = None
